on:
  #workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ftp server
    steps:
      - name: ftp-action
        # You may pin to the exact commit or the version.
        uses: sebastianpopp/ftp-action@ca3f8d253d20ddd6aa658f8cb27fc847fd610882
        # uses: sebastianpopp/ftp-action@v2.0.0
        with:
          # FTP host
          host: ${{ secrets.FREE_FTP_HOST }}
          # FTP user
          user: ${{ secrets.FREE_FTP_USERNAME }}
          # FTP password
          password: ${{ secrets.FREE_FTP_PASSWORD }}
          # Force SSL encryption
          forceSsl: false
          # Local directory
          localDir: '.'
          # Remote directory
          remoteDir: '.'
        
